server:
  port: 8383

spring:
  application:
    name: moon-auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 600000 # 10 minutes
    refresh-token-expiration-ms: 604800000 # 7 days
  security:
    brute-force:
      max-attempts: 5
      lock-duration-ms: 900000 # 15 minutes
    throttling:
      email-resend-ms: 60000 # 1 minute
      password-reset-ms: 300000 # 5 minutes
    email-verification:
      expiration-ms: 86400000 # 24 hours
    password-reset:
      expiration-ms: 1800000 # 30 minutes
  cors:
    allowed-origins: "*"
  mail-service:
    url: ${MAIL_SERVICE_URL}

logging:
  level:
    lk.tech.moonauth: DEBUG
    org.springframework.security: INFO